import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "./components/navbar";
import Footer from "./components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<header className="w-full sticky top-0 left-0 flex items-center justify-start bg-gradient-to-r from-black">
					<Navbar />
				</header>
				{children}
				<footer className="w-screen flex flex-col items-center justify-center bg-black py-2">
					<Footer />
				</footer>
			</body>
		</html>
	);
}
